In [ ]:
##Data Exploration & Leading##

In [55]:
import pandas as pd

In [56]:
df = pd.read_csv("C:\\Users\\vinay\\Downloads\\Walmart.csv")

In [57]:
# Try using the 'python' engine which is more flexible than the default 'c' engine
df = pd.read_csv("C:\\Users\\vinay\\Downloads\\Walmart.csv", engine='python', on_bad_lines='skip')

In [58]:
print(df.shape)

(10051, 11)

In [59]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,5/1/2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,8/3/2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,3/3/2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,8/2/2019,10:37:00,Ewallet,5.3,0.48

In [61]:
df.tail()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
10046,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,3/8/2023,10:10:00,Cash,3.0,0.33
10047,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
10048,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
10049,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
10050,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [62]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [64]:
# all duplicates

df.duplicated().sum()

np.int64(51)

In [65]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [66]:
df.shape

(10000, 11)

In [67]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [68]:
# dropping all rows with missing records

df.dropna(inplace=True)

In [69]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [70]:
df.shape

(9969, 11)

In [71]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [72]:
df['unit_price'] = df['unit_price'].str.replace('$','').astype(float)

In [73]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,5/1/2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,8/3/2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,3/3/2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,8/2/2019,10:37:00,Ewallet,5.3,0.48

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [75]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [76]:
df['total'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,5/1/2019,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,8/3/2019,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,3/3/2019,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,8/2/2019,10:37:00,Ewallet,5.3,0.48,604.17

In [79]:
df.to_csv('walmart_clean_data.csv', index=False)

In [80]:
# Assuming your cleaned data is in a DataFrame named 'df_clean'
import sqlite3
conn = sqlite3.connect('walmart_data.db')
df.to_sql('walmart_clean_data',conn, if_exists='replace', index=False)

# NOW you can run your query
query = "SELECT * FROM walmart_clean_data "
df_result = pd.read_sql_query(query, conn)
df_result

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,5/1/2019,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,8/3/2019,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,3/3/2019,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,8/2/2019,10:37:00,Ewallet,5.3,0.48,604.17
...,...,...,...,...,...,...,...,...,...,...,...,...
9964,9996,WALM056,Rowlett,Fashion accessories,37.00,3.0,3/8/2023,10:10:00,Cash,3.0,0.33,111.00
9965,9997,WALM030,Richardson,Home and lifestyle,58.00,2.0,22/02/21,14:20:00,Cash,7.0,0.48,116.00
9966,9998,WALM050,Victoria,Fashion accessories,52.00,3.0,15/06/23,16:00:00,Credit card,4.0,0.48,156.00
9967,9999,WALM032,Tyler,Home and lifestyle,79.00,2.0,25/02/21,12:25:00,Cash,7.0,0.48,158.00
9968,10000,WALM069,Rockwall,Fashion accessories,62.00,3.0,26/09/20,9:48:00,Cash,3.0,0.33,186.00

In [82]:
import pandas as pd
import sqlite3 # Or another driver like  pymysql

# Establish connection
conn = sqlite3.connect('walmart_data.db')

# Run SQL and load directly into a DataFrame
query = "SELECT * FROM walmart_clean_data WHERE rating > 9.0"
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,5/1/2019,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,8/3/2019,10:29:00,Cash,9.6,0.48,76.40
2,24,WALM067,Haltom City,Electronic accessories,34.56,5.0,17/02/19,11:15:00,Ewallet,9.9,0.33,172.80
3,29,WALM012,Garland,Food and beverages,88.36,5.0,25/01/19,19:48:00,Cash,9.6,0.48,441.80
4,46,WALM056,Rowlett,Electronic accessories,93.96,4.0,9/3/2019,18:00:00,Cash,9.5,0.33,375.84
...,...,...,...,...,...,...,...,...,...,...,...,...
146,961,WALM013,Irving,Fashion accessories,91.98,1.0,18/03/19,15:29:00,Cash,9.8,0.48,91.98
147,962,WALM022,Mesquite,Electronic accessories,20.89,2.0,5/2/2019,18:45:00,Cash,9.8,0.48,41.78
148,968,WALM049,North Richland Hills,Home and lifestyle,81.01,3.0,13/01/19,12:55:00,Credit card,9.3,0.48,243.03
149,969,WALM012,Garland,Health and beauty,15.80,3.0,25/03/19,18:02:00,Cash,9.5,0.48,47.40
150,981,WALM072,Lancaster,Food and beverages,59.59,4.0,19/01/19,12:46:00,Cash,9.8,0.33,238.36

In [83]:
query = "SELECT count(*) FROM walmart_clean_data "
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

   count(*)
0      9969

In [84]:
query = "SELECT distinct payment_method, count(*) FROM walmart_clean_data group by payment_method "
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

  payment_method  count(*)
0           Cash      1832
1    Credit card      4256
2        Ewallet      3881

In [85]:
## Q1. find different payment method and number of transactions , number of qty sold 

query = "SELECT payment_method, count(*) as no_payments, sum(quantity) as no_qty_sold FROM walmart_clean_data group by payment_method "
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

  payment_method  no_payments  no_qty_sold
0           Cash         1832       4984.0
1    Credit card         4256       9567.0
2        Ewallet         3881       8932.0

In [86]:
## Q2. identify the highest rated category in each branch, displaying the branch, category avg rating


query = "select * from (SELECT branch, category, avg(rating) as avg_rating, rank() over(partition by branch order by avg(rating) desc) as rank  FROM walmart_clean_data group by 1,2 ) where rank = 1 "
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

      branch                category  avg_rating  rank
0    WALM001  Electronic accessories    7.450000     1
1    WALM002      Food and beverages    8.250000     1
2    WALM003       Sports and travel    7.500000     1
3    WALM004      Food and beverages    9.300000     1
4    WALM005       Health and beauty    8.366667     1
..       ...                     ...         ...   ...
96   WALM096       Sports and travel    9.600000     1
97   WALM097      Food and beverages    7.675000     1
98   WALM098       Health and beauty    9.800000     1
99   WALM099  Electronic accessories    5.950000     1
100  WALM100       Health and beauty    6.900000     1

[101 rows x 4 columns]

In [87]:
# 3. Calculate the total quantity of items sold  per payment method. list payment_method and total_quantity




query = "SELECT payment_method, sum(quantity) as no_qty_sold FROM walmart_clean_data group by payment_method "
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

  payment_method  no_qty_sold
0           Cash       4984.0
1    Credit card       9567.0
2        Ewallet       8932.0

In [88]:
 ## q4. Determine the average, minimum, and maximum rating of category for each city. list the city, average_rating, min_rating and max_rating.



query = "SELECT city, category, min(rating) as min_rating, max(rating) as max_rating, avg(rating) as avg_rating from walmart_clean_data group by 1, 2" 
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

        City                category  min_rating  max_rating  avg_rating
0    Abilene  Electronic accessories         7.1         8.8    7.966667
1    Abilene     Fashion accessories         4.0         9.0    6.240625
2    Abilene      Food and beverages         6.0         8.9    6.950000
3    Abilene       Health and beauty         9.7         9.7    9.700000
4    Abilene      Home and lifestyle         4.0         9.0    6.096875
..       ...                     ...         ...         ...         ...
508  Weslaco     Fashion accessories         3.0         9.5    5.042012
509  Weslaco      Food and beverages         7.1         9.8    8.733333
510  Weslaco       Health and beauty         4.3         9.2    6.750000
511  Weslaco      Home and lifestyle         3.0         9.2    5.183505
512  Weslaco       Sports and travel         4.1         7.1    5.600000

[513 rows x 5 columns]

In [89]:
## Q5. calculate the total profit for each category by considering total_profit as () unit_price * quantity * profit_margin). list category and total_profit, ordered from highest to lowest profit.




query = "select category, sum(total) as total_revenue, sum(total * profit_margin) as profit FROM walmart_clean_data group by 1  "
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

                 category  total_revenue       profit
0  Electronic accessories       78175.03   30772.4895
1     Fashion accessories      489480.90  192314.8932
2      Food and beverages       53471.28   21552.8622
3       Health and beauty       46851.18   18671.7345
4      Home and lifestyle      489250.06  192213.6381
5       Sports and travel       52497.93   20613.8082

In [90]:
## Q6. determine the most common payment method for each branch. display branch and the preferred_payment_method.




query = "WITH cte as (select branch, payment_method, count(*) as total_trans, rank() over(partition by branch order by count(*) desc) as rank FROM walmart_clean_data group by 1, 2) select * from cte where rank = 1  "
df = pd.read_sql_query(query, conn)
df_result = pd.read_sql_query(query, conn)

# Display the table
df_result

     branch payment_method  total_trans  rank
0   WALM001        Ewallet           45     1
1   WALM002        Ewallet           37     1
2   WALM003    Credit card          115     1
3   WALM004        Ewallet           44     1
4   WALM005        Ewallet           56     1
..      ...            ...          ...   ...
95  WALM096        Ewallet           50     1
96  WALM097        Ewallet           38     1
97  WALM098        Ewallet           44     1
98  WALM099    Credit card           83     1
99  WALM100        Ewallet           42     1

[100 rows x 4 columns]